name: file_logger
description: "A simple flutter file logger with a page to view the stored logs"
homepage: https://github.com/andriensis/Flutter-Logger
version: 1.1.1

topics:
  - logging

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.5
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: 'Log tags page'
    path: doc/log-tags.png
  - description: 'Logs page with logs for tealium tag'
    path: doc/log-page.png